version: "3"

services:
  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/cezerin:/var/www/cezerin
    ports:
      - 80:80
    links:
      - web

  web:
    image: "cezerin/cezerin:latest"
    volumes:
      - /var/www/cezerin:/var/www/cezerin
    depends_on:
      - db
    links:
      - db

  db:
    image: "mongo:latest"
    volumes:
      - /var/www/db:/data/db
